apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: app-demo
      spec:
        containers:
        - name: zookeeper
          image: 192.168.5.103:5000/qibei/zookeeper
          ports:
          - containerPort: 2181
